# Factorisation de matrice
## Première approche "naïve"

Nous implémentons un modèle simple de filtrage collaboratif, basé sur la factorisation de matrice. 

### Installation et import des bibliothèques

In [2]:
import sys
!{sys.executable} -m pip install pandas
!{sys.executable} -m pip install torch torchvision torchaudio
!{sys.executable} -m pip install pytorch-lightning


[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import pandas as pd
import numpy as np
import pytorch_lightning as pl
import torch
import torch.nn as nn
import torch.nn.functional as F
from pytorch_lightning.loggers import TensorBoardLogger

### Récupération des csv, et description des `DataFrames`

In [2]:
genome_scores = pd.read_csv("../data/raw/genome-scores.csv")
genome_tags = pd.read_csv("../data/raw/genome-tags.csv")
links = pd.read_csv("../data/raw/links.csv")
movies = pd.read_csv("../data/raw/movies.csv")
ratings = pd.read_csv("../data/raw/ratings.csv")
tags = pd.read_csv("../data/raw/tags.csv")

In [5]:
l = [genome_scores, genome_tags, links, movies, ratings, tags]

for elt in l: 
    display(elt.head())
    display(elt.info())


movieId  tagId  relevance
0        1      1    0.02500
1        1      2    0.02500
2        1      3    0.05775
3        1      4    0.09675
4        1      5    0.14675

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11709768 entries, 0 to 11709767
Data columns (total 3 columns):
 #   Column     Dtype  
---  ------     -----  
 0   movieId    int64  
 1   tagId      int64  
 2   relevance  float64
dtypes: float64(1), int64(2)
memory usage: 268.0 MB


None

tagId           tag
0      1           007
1      2  007 (series)
2      3  18th century
3      4         1920s
4      5         1930s

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1128 entries, 0 to 1127
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   tagId   1128 non-null   int64 
 1   tag     1128 non-null   object
dtypes: int64(1), object(1)
memory usage: 17.8+ KB


None

movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27278 entries, 0 to 27277
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   movieId  27278 non-null  int64  
 1   imdbId   27278 non-null  int64  
 2   tmdbId   27026 non-null  float64
dtypes: float64(1), int64(2)
memory usage: 639.5 KB


None

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27278 entries, 0 to 27277
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   movieId  27278 non-null  int64 
 1   title    27278 non-null  object
 2   genres   27278 non-null  object
dtypes: int64(1), object(2)
memory usage: 639.5+ KB


None

userId  movieId  rating   timestamp
0       1        2     3.5  1112486027
1       1       29     3.5  1112484676
2       1       32     3.5  1112484819
3       1       47     3.5  1112484727
4       1       50     3.5  1112484580

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000263 entries, 0 to 20000262
Data columns (total 4 columns):
 #   Column     Dtype  
---  ------     -----  
 0   userId     int64  
 1   movieId    int64  
 2   rating     float64
 3   timestamp  int64  
dtypes: float64(1), int64(3)
memory usage: 610.4 MB


None

userId  movieId            tag   timestamp
0      18     4141    Mark Waters  1240597180
1      65      208      dark hero  1368150078
2      65      353      dark hero  1368150079
3      65      521  noir thriller  1368149983
4      65      592      dark hero  1368150078

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 465564 entries, 0 to 465563
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype 
---  ------     --------------   ----- 
 0   userId     465564 non-null  int64 
 1   movieId    465564 non-null  int64 
 2   tag        465548 non-null  object
 3   timestamp  465564 non-null  int64 
dtypes: int64(3), object(1)
memory usage: 14.2+ MB


None

In [6]:
print(f"Il y a {ratings.movieId.nunique()} films dans notre jeu de données.")
print(f"Il y a {ratings.userId.nunique()} utilisateurs dans notre jeu de données.")

Il y a 26744 films dans notre jeu de données.
Il y a 138493 utilisateurs dans notre jeu de données.


In [10]:
ratings.movieId.values

array([    2,    29,    32, ..., 69644, 70286, 71619], dtype=int64)

### Ajout de la date sur les `DataFrames` **`ratings`** et **`tags`**

In [6]:
ratings2 = ratings.copy()
tags2 = tags.copy()

ratings2["date"] = pd.to_datetime(ratings2["timestamp"], unit = "s")
tags2["date"] = pd.to_datetime(tags2["timestamp"], unit = "s")

display(ratings2.head())
display(tags2.head())

userId  movieId  rating   timestamp                date
0       1        2     3.5  1112486027 2005-04-02 23:53:47
1       1       29     3.5  1112484676 2005-04-02 23:31:16
2       1       32     3.5  1112484819 2005-04-02 23:33:39
3       1       47     3.5  1112484727 2005-04-02 23:32:07
4       1       50     3.5  1112484580 2005-04-02 23:29:40

userId  movieId            tag   timestamp                date
0      18     4141    Mark Waters  1240597180 2009-04-24 18:19:40
1      65      208      dark hero  1368150078 2013-05-10 01:41:18
2      65      353      dark hero  1368150079 2013-05-10 01:41:19
3      65      521  noir thriller  1368149983 2013-05-10 01:39:43
4      65      592      dark hero  1368150078 2013-05-10 01:41:18

In [7]:
print("Étendue des ratings : de ", ratings2.date.min(), " à ", ratings2.date.max())
print("Étendue des tags : de", tags2.date.min(), " à ", tags2.date.max())

Étendue des ratings : de  1995-01-09 11:46:44  à  2015-03-31 06:40:02
Étendue des tags : de 2005-12-24 13:00:10  à  2015-03-31 03:09:12


### Construction de la matrice d'interaction
Observons le nombre de modalités dans les variables userId et movieId.

In [8]:
ratings.nunique()

userId         138493
movieId         26744
rating             10
timestamp    15351121
dtype: int64

L'objectif est de construire une matrice $A\in \mathbb{R}^{m*n}$ dont les éléments représenteraient les notes explicites, et où : 
* $m$ est le nombre total d'utilisateurs (égal à **`ratings.userId.nunique()`**)
* $n$ est le nombre total de films (égal à **`ratings.movieId.nunique()`**)


Avec les nombres bruts obtenus, on aurait une matrice de taille $138~493 * 26~744$, ce qui correspond à $3.7$ milliards d'éléments. Dû à des limitations techniques, nous sommes contraints de réduire notre jeu de données de manière significative.

In [9]:
try : 
    ratings.copy().pivot(index = "userId", columns = "movieId", values = "rating")
except ValueError: # un overflow survient, on obtient une dimension négative.
    print("La transformation a échoué, les dimensions d'entrée sont trop larges")

c:\Users\pc-04\Documents\Template_MLOps_movie_recommandation\.venv\lib\site-packages\pandas\core\reshape\reshape.py:125: RuntimeWarning: overflow encountered in scalar multiply
  num_cells = num_rows * num_columns


La transformation a échoué, les dimensions d'entrée sont trop larges


In [10]:
# On réduit le jeu de données via sample (on ne garde que 0.1% du jeu de données), puis on utilise pivot() pour générer la matrice d'interactions
interactions = ratings.sample(frac = 0.001).reset_index(drop = True).pivot(index = "userId", columns = "movieId", values = "rating")

display(interactions)

# Observation de la disparité des données
print(f"Il y a {interactions.isna().sum().sum()} valeurs manquantes.\n\
Au total, il y a {interactions.size} éléments dans la DataFrame interactions\n\
Il y a donc {(interactions.isna().sum().sum()/interactions.size)*100:.3f}% de valeurs manquantes\n")
interactions.loc[:, 0:20].info()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
11          NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
18          NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
22          NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
23          NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
24          NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...     ...     ...     ...     ...     ...     ...     ...   
138437      NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
138457      NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
138470      NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
138477      NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
138486      NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  9       10      ...  115617  115831  116977  117176  117590  118700  \
userId                   ...                                                   
11          NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
18          NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
22          NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
23          NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
24          NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...     ...  ...     ...     ...     ...     ...     ...     ...   
138437      NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
138457      NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
138470      NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
138477      NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
138486      NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  118997  126283  129415  130382  
userId                                   
11          NaN     NaN     NaN     NaN  
18          NaN     NaN     NaN     NaN  
22          NaN     NaN     NaN     NaN  
23          NaN     NaN     NaN     NaN  
24          NaN     NaN     NaN     NaN  
...         ...     ...     ...     ...  
138437      NaN     NaN     NaN     NaN  
138457      NaN     NaN     NaN     NaN  
138470      NaN     NaN     NaN     NaN  
138477      NaN     NaN     NaN     NaN  
138486      NaN     NaN     NaN     NaN  

[16342 rows x 4623 columns]

Il y a 75529066 valeurs manquantes.
Au total, il y a 75549066 éléments dans la DataFrame interactions
Il y a donc 99.974% de valeurs manquantes

<class 'pandas.core.frame.DataFrame'>
Index: 16342 entries, 11 to 138486
Data columns (total 20 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   1       45 non-null     float64
 1   2       25 non-null     float64
 2   3       8 non-null      float64
 3   4       4 non-null      float64
 4   5       11 non-null     float64
 5   6       30 non-null     float64
 6   7       14 non-null     float64
 7   8       3 non-null      float64
 8   9       2 non-null      float64
 9   10      20 non-null     float64
 10  11      19 non-null     float64
 11  12      4 non-null      float64
 12  13      1 non-null      float64
 13  14      8 non-null      float64
 14  15      2 non-null      float64
 15  16      18 non-null     float64
 16  17      21 non-null     float64
 17  18      3 non-null      float64
 18  19  

La factorisation de matrice (_Matrix Factorization_ en anglais) est une classe de modèles de filtrage collaboratif. **L'idée essentielle est de considérer la matrice d'interactions comme étant le produit de deux matrices de dimensions inférieures à la matrice d'origine.** Cette décomposition permet de mettre en lumière les caractéristiques implicites du système.

Ainsi, on définit deux nouvelles matrices :
* la **matrice latente des utilisateurs** $P \in \mathbb{R}^{m*k}$
* la **matrice latente des films** $Q \in \mathbb{R}^{n*k}$

Que vaut le paramètre $k$ ? Appelé **taille du facteur latent**, ce dernier est strictement inférieur aux dimensions d'origine $m$ et $n$.

Le produit des matrices latentes donne une matrice $\hat{A}$ de même taille que $A$. Cette relation est donnée via l'équation suivante : 

$ \hat{A} = P*Q^{T}$, avec $\hat{A} \approx A$

Cette approximation ne fait sens que lorsque l'on compare les éléments de $\hat{A}$ avec ceux non manquants dans $A$ ; on définit ainsi l'ensemble des observations pertinentes $\kappa$ :

$\kappa = \{(u, i)~|~A_{ui}~est~connu \}$

Lors de l'entraînement du modèle, nous allons chercher à minimiser l'erreur moyenne quadratique (MSE) entre les évaluations prédites et réelles, tout en prenant en considération les biais éventuels touchant les utilisateurs comme les films. La fonction de perte à minimiser devient alors la suivante :  

$ \underset{P, Q, b}{argmin}\underset{i,j\in{\kappa}}\sum\|A_{ij} - \hat{A{ij}}\|^{2} + \lambda (\|P\|^2_F + \|Q\|_F^2 + b_u^2 + b_i^2)$

Où $\lambda$ dénote le facteur de régularisation.

Les paramètres du modèle peuvent être appris avec un algorithme usuel d'optimisation tel que la descente de gradient stochastique (SGD) ou Adam.

In [11]:
interactions = np.nan_to_num(interactions)


interactions

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

### Construction sur PyTorch

In [12]:
class MatrixFactorization(nn.Module):
    def __init__(self, embedding_dims, num_users, num_items, sparse = False, **kwargs):
        super().__init__()
        self.sparse = sparse

        self.user_embedding = nn.Embedding(num_users, embedding_dims, sparse = sparse)
        self.user_bias = nn.Embedding(num_users, 1, sparse = sparse)

        self.item_embedding = nn.Embedding(num_items, embedding_dims, sparse = sparse)
        self.item_bias = nn.Embedding(num_items, 1, sparse = sparse)

        for param in self.parameters():
            nn.init.normal_(param, std=0.01)
    
    def forward(self, user_id, item_id):
        P_u = self.user_embedding(user_id)
        b_u = self.user_bias(user_id).flatten()

        Q_i = self.item_embedding(item_id)
        b_i = self.item_bias(item_id).flatten()

        return (P_u*Q_i).sum(-1) + b_u + b_i

In [14]:
model = MatrixFactorization(5, 5, 5)

In [15]:
model.state_dict()

OrderedDict([('user_embedding.weight',
              tensor([[-1.2568e-02, -4.6730e-03, -3.3334e-03,  1.2265e-03, -1.2654e-02],
                      [ 3.1120e-03, -3.6110e-03,  1.5917e-02,  2.5636e-02, -1.6199e-03],
                      [-1.2424e-02,  2.3483e-02,  3.1398e-03,  6.0457e-03,  2.0491e-03],
                      [ 2.3703e-02, -1.1297e-03,  1.5363e-02, -4.1876e-07, -8.4021e-03],
                      [-7.7370e-03, -1.0735e-02,  1.1534e-02, -1.4830e-02,  1.7291e-03]])),
             ('user_bias.weight',
              tensor([[-0.0015],
                      [-0.0062],
                      [-0.0020],
                      [-0.0199],
                      [-0.0085]])),
             ('item_embedding.weight',
              tensor([[ 0.0071,  0.0014, -0.0112, -0.0096,  0.0036],
                      [ 0.0082, -0.0110, -0.0076, -0.0130, -0.0089],
                      [ 0.0035,  0.0033,  0.0100, -0.0104,  0.0066],
                      [-0.0011,  0.0094, -0.0031,  0.0111,  0.008

In [27]:
ratings.loc[(ratings.userId == 1), ["userId"]]

userId
0         1
1         1
2         1
3         1
4         1
..      ...
170       1
171       1
172       1
173       1
174       1

[175 rows x 1 columns]

In [27]:
import pandas as pd
import os

names = ['user_id', 'item_id', 'rating', 'timestamp']
udata = pd.read_csv(r'..\data\raw\u.data', sep = '\t', names=names)
ratings = pd.read_csv("../data/raw/ratings.csv")

In [28]:
display(udata.head())
display(ratings.head())

user_id  item_id  rating  timestamp
0      196      242       3  881250949
1      186      302       3  891717742
2       22      377       1  878887116
3      244       51       2  880606923
4      166      346       1  886397596

userId  movieId  rating   timestamp
0       1        2     3.5  1112486027
1       1       29     3.5  1112484676
2       1       32     3.5  1112484819
3       1       47     3.5  1112484727
4       1       50     3.5  1112484580

In [16]:
print(udata.info())
ratings.info(show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   user_id    100000 non-null  int64
 1   item_id    100000 non-null  int64
 2   rating     100000 non-null  int64
 3   timestamp  100000 non-null  int64
dtypes: int64(4)
memory usage: 3.1 MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000263 entries, 0 to 20000262
Data columns (total 4 columns):
 #   Column     Non-Null Count     Dtype  
---  ------     --------------     -----  
 0   userId     20000263 non-null  int64  
 1   movieId    20000263 non-null  int64  
 2   rating     20000263 non-null  float64
 3   timestamp  20000263 non-null  int64  
dtypes: float64(1), int64(3)
memory usage: 610.4 MB


In [62]:
print(ratings.userId.max())
print(ratings.userId.nunique())

138493
138493


In [44]:
print(ratings.movieId.max())
print(ratings.movieId.nunique())

131262
26744


In [26]:
udata.item_id.unique()

array([ 242,  302,  377, ..., 1637, 1630, 1641], dtype=int64)

In [60]:
import numpy as np
temp = np.array(range(131263))
temp2 = []
for elt in temp:
    if elt not in ratings.movieId.values:
        temp2.append(elt)


KeyboardInterrupt: 

In [61]:
temp2

[0,
 91,
 221,
 323,
 557,
 578,
 622,
 646,
 669,
 677,
 686,
 689,
 740,
 811,
 817,
 863,
 883,
 978,
 995,
 1048,
 1072,
 1074,
 1108,
 1182,
 1195,
 1205,
 1229,
 1239,
 1294,
 1338,
 1362,
 1402,
 1403,
 1418,
 1435,
 1451,
 1452,
 1469,
 1478,
 1481,
 1491,
 1492,
 1494,
 1505,
 1506,
 1512,
 1521,
 1530,
 1536,
 1540,
 1560,
 1576,
 1607,
 1618,
 1634,
 1637,
 1638,
 1691,
 1700,
 1712,
 1736,
 1737,
 1741,
 1745,
 1751,
 1758,
 1761,
 1763,
 1766,
 1775,
 1778,
 1786,
 1790,
 1800,
 1802,
 1803,
 1808,
 1813,
 1818,
 1823,
 1828,
 1838,
 1847,
 1868,
 2228,
 2645,
 3027,
 3366,
 3416,
 3482,
 3532,
 3815,
 3842,
 3935]

In [57]:
if 10000000 not in ratings.movieId:
    print("a")

In [59]:
ratings.movieId.values

array([    2,    29,    32, ..., 69644, 70286, 71619], dtype=int64)

In [64]:
for c, elt in enumerate(ratings.movieId):
    if c%1000 == 0:
        print(elt)

2
527
4967
4321
110
1094
3198
1
2916
342
2916
593
1953
6874
4887
14
5308
1104
4571
5669
360
2922
5981
558
50
39427
593
48385
32587
515
3996
23
368
2671
2183
43871
5957
8636
30749
1865
2396
1562
5313
266
2542
1407
27843
428
35836
2115
56171
333
5570
2058
909
49220
39292
1296
2917
51662
2108
1939
15
367
5378
3114
3950
8371
3067
2245
256
52
77455
104
2404
2174
6003
1752
1060
5989
1061
908
7367
2060
1274
30
5520
1013
356
2701
1408
105
54503
589
8910
8638
2699
231
249
6936
1387
1210
42094
3751
1732
1203
1213
1377
5286
344
150
940
5246
485
1200
4508
2370
661
1088
3578
736
2628
1208
70932
64575
1279
2140
2599
1792
587
3098
6218
58559
1589
3273
158
52604
3510
3247
1676
1197
48394
1729
102058
1373
4890
2273
2275
6995
1208
71282
3635
442
4823
4995
434
608
1224
1791
585
1968
75395
1945
694
27815
7283
910
1196
3735
6711
265
5941
2628
637
2657
3301
2144
1960
26939
953
153
2115
1284
4351
747
41569
1320
111
448
3082
485
422
1552
1196
1759
266
4815
2427
1394
904
2139
266
2289
8833
1275
4056
208
6754
3

In [65]:
ratings.movieId.value_counts()

movieId
296       67310
356       66172
318       63366
593       63299
480       59715
          ...  
125545        1
78873         1
112907        1
112909        1
110510        1
Name: count, Length: 26744, dtype: int64

In [68]:
temp_dict = {}

for elt in ratings.movieId:
    if elt not in temp_dict:
        

In [69]:
len(temp_dict)

2

In [83]:
temp_dict = {}
test = [200_000, 333_000, 1_000_000, 50_000, 200_000, 1_000_000]

for elt in test:
    flag = 1
    for k, v in temp_dict.items():
        if elt == v:
            elt = k
            print(f"{elt} est remplacé par {k}")
            flag = 0
    if flag:
        key = len(temp_dict)
        print("new key")
        temp_dict[key] = elt
        elt = key

print(temp_dict)
print(test)
    

new key
new key
new key
new key
0 est remplacé par 0
2 est remplacé par 2
{0: 200000, 1: 333000, 2: 1000000, 3: 50000}
[200000, 333000, 1000000, 50000, 200000, 1000000]


In [75]:
l = [333, 444, 555, 666, 999]
temp_dict = {}
for elt in l: 
    for k, v in temp_dict.items(): 
        if elt in v:
            print()
    else:

False

In [110]:
test_df = pd.DataFrame({"a" : [1, 2, 3, 4, 5, 6], "b" : [200_000, 333_000, 1_000_000, 50_000, 200_000, 1_000_000], "c": [10000, 10000, 10000, 10000, 0, 1]})
test_df

a        b      c
0  1   200000  10000
1  2   333000  10000
2  3  1000000  10000
3  4    50000  10000
4  5   200000      0
5  6  1000000      1

In [90]:
def temp_func(elt, temp_dict = {}):
    for k, v in temp_dict.items():
        if elt == v:
            print(f"{elt} est remplacé par {k}")
            return k
    key = len(temp_dict)
    print("new key")
    temp_dict[key] = elt
    return key

In [98]:
test_df.b.apply(temp_func)

200000 est remplacé par 0
333000 est remplacé par 1
1000000 est remplacé par 2
50000 est remplacé par 3
200000 est remplacé par 0
1000000 est remplacé par 2


0    0
1    1
2    2
3    3
4    0
5    2
Name: b, dtype: int64

In [127]:
def reset_indices(df, col_names = []):
    df_temp = df.copy()
    for col in col_names:
        def temp_func(elt, temp_dict = {}):
            for k, v in temp_dict.items():
                if elt == v:
                    #print(f"{elt} est remplacé par {k}")
                    return k
            key = len(temp_dict)
            #print("new key")
            temp_dict[key] = elt
            return key
        df_temp[col] = df_temp[col].apply(temp_func)
    return df_temp


In [128]:
aaa = reset_indices(ratings, col_names=["movieId"])

KeyboardInterrupt: 

In [114]:
aaa.head()

a  b  c
0  1  0  0
1  2  1  0
2  3  2  0
3  4  3  0
4  5  0  1

In [155]:
from sklearn.preprocessing import LabelEncoder as le

temp = le().fit_transform(ratings["movieId"])

In [156]:
temp = pd.DataFrame(data = temp)


temp

0
0             1
1            28
2            31
3            46
4            49
...         ...
20000258  13754
20000259  13862
20000260  13875
20000261  13993
20000262  14277

[20000263 rows x 1 columns]

In [160]:
ratings["movieId"] = temp[0]

In [161]:
ratings

userId  movieId  rating   timestamp
0              1        1     3.5  1112486027
1              1       28     3.5  1112484676
2              1       31     3.5  1112484819
3              1       46     3.5  1112484727
4              1       49     3.5  1112484580
...          ...      ...     ...         ...
20000258  138493    13754     4.5  1258126920
20000259  138493    13862     4.5  1259865108
20000260  138493    13875     3.0  1260209457
20000261  138493    13993     5.0  1258126944
20000262  138493    14277     2.5  1255811136

[20000263 rows x 4 columns]

In [166]:
ratings = pd.read_csv("../data/raw/ratings.csv")


In [167]:
from sklearn.preprocessing import LabelEncoder as le

ratings.head()

def reset_id(df, col_name):
    temp = pd.DataFrame(le().fit_transform(df[col_name]))
    df[col_name] = temp
    return df

test = reset_id(ratings, "movieId")

In [172]:
test.userId -=1

In [174]:
test.userId.min()

0